version: "3.3"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile-dev
        image: api:dev
        ports:
            - 8080:8080
        environment:
            DATABASE_HOST: testdb
            DATABASE_PORT: 5432

        volumes:
            - .:/app
        working_dir: /app
        stdin_open: true
        tty: true
        entrypoint: bash
    db:
        image: postgres
        environment:
            POSTGRES_USER: staging
            POSTGRES_PASSWORD: password
            POSTGRES_DATABASE: postgres
    testdb:
        image: postgres
        environment:
            POSTGRES_USER: testing
            POSTGRES_PASSWORD: password
            POSTGRES_DB: testdb
